[2025-06-03T14:38:47.512-0300] {processor.py:161} INFO - Started process (PID=71465) to work on /home/walterg/Documentos/Data_projects/DW_AIRFLOW_DBT_PART_ONE/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-03T14:38:47.513-0300] {processor.py:830} INFO - Processing file /home/walterg/Documentos/Data_projects/DW_AIRFLOW_DBT_PART_ONE/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-03T14:38:47.513-0300] {logging_mixin.py:188} INFO - [2025-06-03T14:38:47.513-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/walterg/Documentos/Data_projects/DW_AIRFLOW_DBT_PART_ONE/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-03T14:38:47.516-0300] {logging_mixin.py:188} INFO - [2025-06-03T14:38:47.516-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/walterg/Documentos/Data_projects/DW_AIRFLOW_DBT_PART_ONE/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-03T14:38:47.516-0300] {logging_mixin.py:188} INFO - [2025-06-03T14:38:47.516-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-03T14:38:47.517-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/walterg/Documentos/Data_projects/DW_AIRFLOW_DBT_PART_ONE/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-03T14:38:47.525-0300] {processor.py:183} INFO - Processing /home/walterg/Documentos/Data_projects/DW_AIRFLOW_DBT_PART_ONE/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-06-03T14:39:33.984-0300] {processor.py:161} INFO - Started process (PID=72189) to work on /home/walterg/Documentos/Data_projects/DW_AIRFLOW_DBT_PART_ONE/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-03T14:39:33.990-0300] {processor.py:830} INFO - Processing file /home/walterg/Documentos/Data_projects/DW_AIRFLOW_DBT_PART_ONE/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-03T14:39:33.991-0300] {logging_mixin.py:188} INFO - [2025-06-03T14:39:33.990-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/walterg/Documentos/Data_projects/DW_AIRFLOW_DBT_PART_ONE/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-03T14:39:33.994-0300] {logging_mixin.py:188} INFO - [2025-06-03T14:39:33.993-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/walterg/Documentos/Data_projects/DW_AIRFLOW_DBT_PART_ONE/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-03T14:39:33.994-0300] {logging_mixin.py:188} INFO - [2025-06-03T14:39:33.994-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-03T14:39:33.994-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/walterg/Documentos/Data_projects/DW_AIRFLOW_DBT_PART_ONE/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-03T14:39:34.003-0300] {processor.py:183} INFO - Processing /home/walterg/Documentos/Data_projects/DW_AIRFLOW_DBT_PART_ONE/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2025-06-03T14:40:24.745-0300] {processor.py:161} INFO - Started process (PID=72823) to work on /home/walterg/Documentos/Data_projects/DW_AIRFLOW_DBT_PART_ONE/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-03T14:40:24.750-0300] {processor.py:830} INFO - Processing file /home/walterg/Documentos/Data_projects/DW_AIRFLOW_DBT_PART_ONE/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-03T14:40:24.751-0300] {logging_mixin.py:188} INFO - [2025-06-03T14:40:24.751-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/walterg/Documentos/Data_projects/DW_AIRFLOW_DBT_PART_ONE/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-03T14:40:24.754-0300] {logging_mixin.py:188} INFO - [2025-06-03T14:40:24.753-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/walterg/Documentos/Data_projects/DW_AIRFLOW_DBT_PART_ONE/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-03T14:40:24.754-0300] {logging_mixin.py:188} INFO - [2025-06-03T14:40:24.754-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-03T14:40:24.754-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/walterg/Documentos/Data_projects/DW_AIRFLOW_DBT_PART_ONE/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-03T14:40:24.763-0300] {processor.py:183} INFO - Processing /home/walterg/Documentos/Data_projects/DW_AIRFLOW_DBT_PART_ONE/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2025-06-03T14:41:11.613-0300] {processor.py:161} INFO - Started process (PID=73402) to work on /home/walterg/Documentos/Data_projects/DW_AIRFLOW_DBT_PART_ONE/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-03T14:41:11.614-0300] {processor.py:830} INFO - Processing file /home/walterg/Documentos/Data_projects/DW_AIRFLOW_DBT_PART_ONE/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-03T14:41:11.615-0300] {logging_mixin.py:188} INFO - [2025-06-03T14:41:11.614-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/walterg/Documentos/Data_projects/DW_AIRFLOW_DBT_PART_ONE/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-03T14:41:11.618-0300] {logging_mixin.py:188} INFO - [2025-06-03T14:41:11.617-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/walterg/Documentos/Data_projects/DW_AIRFLOW_DBT_PART_ONE/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-03T14:41:11.618-0300] {logging_mixin.py:188} INFO - [2025-06-03T14:41:11.618-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-03T14:41:11.618-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/walterg/Documentos/Data_projects/DW_AIRFLOW_DBT_PART_ONE/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-03T14:41:11.626-0300] {processor.py:183} INFO - Processing /home/walterg/Documentos/Data_projects/DW_AIRFLOW_DBT_PART_ONE/.venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
